name: （中文）提交 脚本的BUG
description: 如果脚本出现BUG，在这里提交问题
labels:
  - bug
title: "[Bug] <问题标题>"
body:
  - type: markdown
    attributes:
      value: "## 欢迎使用本油猴脚本！"

  - type: markdown
    attributes:
      value: |
        感谢你拨冗提交油猴脚本的问题。在提交之前，请仔细阅读并遵守以下指引，以确保你的问题能够被尽快解决。  
        带有星号（*）的选项为必填，其他可选填。**如果你填写的资料不符合规范，维护者可能不予回复，并直接关闭这个 issue。**
        如果你可以自行 debug 并且修正，我们随时欢迎你提交 Pull Request，将你的修改合并到上游。

  - type: checkboxes
    id: ensure
    attributes:
      label: "先决条件"
      description: "若以下任意选项不适用，请勿提交这个 issue，因为我们会把它关闭"
      options:
        - label: "我使用的是**本仓库**最新版本的油猴脚本"
          required: true
        - label: "我已经在 [Issue Tracker](……/) 中找过我要提出的 bug，**并且没有找到相关问题**"
          required: true

  - type: markdown
    attributes:
      value: "## 脚本环境"
  - type: markdown
    attributes:
      value: |
        请附上这个问题适用的环境，以帮助我们迅速定位问题并解决。若你提供的信息不足，我们将关闭
        这个 issue 并要求你提供更多信息。

  - type: input
    attributes:
      label: "使用的脚本名称"
      description: ""
    validations:
      required: true

  - type: dropdown
    id: scriptruncontainer
    attributes:
      label: "脚本运行的容器"
      description: "勾选运行脚本的环境"
      multiple: false
      options:
        - 扩展-暴力猴（Violentmonkey）
        - 扩展-暴力猴测试版（Violentmonkey BETA）
        - 扩展-篡改猴（TamperMonkey）
        - 扩展-篡改猴测试版（TamperMonkey BETA）
        - 扩展-脚本猫（ScriptCat）
        - Via浏览器
        - X浏览器
        - 其它

  - type: input
    attributes:
      label: "扩展版本"
      description: "如果使用扩展加载的脚本，请填写当前扩展的版本"
    validations:
      required: false


  - type: markdown
    attributes:
      value: "## 脚本的相关信息"
  - type: markdown
    attributes:
      value: |
        请附上与这个问题直接相关的相应信息，以帮助我们迅速定位问题并解决。  
        若你提供的信息不足，我们将关闭这个 issue 并要求你提供更多信息。

  - type: textarea
    attributes:
      label: "问题描述"
      placeholder: "在这里详细叙述你的问题，帮助我们理解（支持 Markdown 语法）"
    validations:
      required: true

  - type: textarea
    attributes:
      label: "复现步骤"
      placeholder: "在这里提供问题的具体重现步骤（支持 Markdown 语法）"