name: （中文）提交 脚本的BUG
description: 如果脚本出现BUG，在这里提交问题
labels:
  - bug
title: "[Bug] "
body:
  - type: markdown
    attributes:
      value: "## 欢迎使用本油猴脚本！"

  - type: markdown
    attributes:
      value: |
        感谢你拨冗提交油猴脚本的问题。在提交之前，请仔细阅读并遵守以下指引，以确保你的问题能够被尽快解决。  
        带有星号（*）的选项为必填，其他可选填。
        请确保该问题是脚本已有的功能未正常生效的情况，而非新功能请求。
        **如果你填写的资料不符合规范，维护者可能不予回复，并直接关闭这个 issue。**
        如果你可以自行 debug 并且修正，我们随时欢迎你提交 Pull Request，将你的修改合并到上游。

  - type: checkboxes
    id: ensure
    attributes:
      label: 先决条件
      description: "若以下任意选项不适用，请勿提交这个 issue，因为我们会把它关闭"
      options:
        - label: "我使用的是**本仓库**最新版本的油猴脚本"
          required: true
        - label: "我已经在 [Issue Tracker](……/) 中找过我要提出的 bug，**并且没有找到相关问题**"
          required: true

  - type: markdown
    attributes:
      value: "## 脚本环境"
  - type: markdown
    attributes:
      value: |
        请附上这个问题适用的环境，以帮助我们迅速定位问题并解决。若你提供的信息不足，我们将关闭
        这个 issue 并要求你提供更多信息。

  - type: dropdown
    id: scriptruncontainer
    attributes:
      label: 脚本运行的容器
      description: "勾选运行脚本的环境"
      multiple: false
      options:
        - 扩展-暴力猴（Violentmonkey）
        - 扩展-暴力猴测试版（Violentmonkey BETA）
        - 扩展-篡改猴（TamperMonkey）
        - 扩展-篡改猴测试版（TamperMonkey BETA）
        - 扩展-脚本猫（ScriptCat）
        - 扩展-Stay
        - Via浏览器
        - X浏览器
        - 其它
    validations:
      required: true

  - type: input
    attributes:
      label: 扩展版本
      description: "如果脚本运行的容器是浏览器扩展，请填写版本号"
    validations:
      required: false

  - type: dropdown
    id: scriptname
    attributes:
      label: 脚本名称
      description: "勾选使用的脚本"
      multiple: false
      options:
        - 【移动端】百度系优化
        - 【移动端】微博优化
        - 【移动端】bilibili优化
        - 【移动端】MT论坛优化
        - 抖音优化
        - 简书优化
        - 图片右键菜单
        - 网盘链接识别
        - 小红书优化
        - CSDN优化
        - GreasyFork优化
        - MT论坛优化
        - 网页调试
        - 模拟竖屏
        - CookieManager
        - 其它(请在下方填写脚本名称)
    validations:
      required: true

  - type: dropdown
    id: browserType
    attributes:
      label: 浏览器
      description: "勾选运行脚本的浏览器，如果脚本运行的容器勾选了其它或者是浏览器，那这里选其它就行"
      multiple: false
      options:
        - Chrome
        - Firefox
        - Safari
        - 其它(请在问题描述内填写浏览器名称)
    validations:
      required: true

  - type: input
    attributes:
      label: 浏览器内核版本
      description: "请填写运行脚本的浏览器内核版本，如果是套壳浏览器，请填写webview的版本"
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## 脚本的相关信息"

  - type: markdown
    attributes:
      value: |
        请附上与这个问题直接相关的相应信息，以帮助我们迅速定位问题并解决。  
        若你提供的信息不足，我们将关闭这个 issue 并要求你提供更多信息。
        提示：可以上传问题截图或者录屏以便快速定位问题

  - type: textarea
    attributes:
      label: 问题描述 & 复现步骤
      placeholder: "在这里详细叙述你的问题及具体重现步骤，可以录视频上传（支持 Markdown 语法）"
    validations:
      required: true
