name: 【移动端】百度系优化

on:
  push:
    branches: ["dev"]
    paths:
      - "packages/【移动端】百度系优化/**"
      - "!packages/【移动端】百度系优化/README.md"
      - "!packages/【移动端】百度系优化/dist/*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: set git
        run: |
          git config --global core.symlinks false

      - name: 校验
        uses: actions/checkout@v3

      - uses: volta-cli/action@v4

      - name: 设置Node和pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: 切换到项目目录下
        run: cd ./packages/【移动端】百度系优化
      - name: 安装依赖
        run: pnpm install
      - name: 开始构建
        run: pnpm run build:all
